import flask

app = flask.Flask(__name__)
app.config['SECRET_KEY'] = 'IPmwYmXQJirnGJIjitOIVViGuySNsNNfFluAWVDgOONPRkszzhSUCosxeRpEjLPFYCwGsAVSDnCMUYkMTKEBaCLOEBckrWCYALevkuLqaUXhEdWKcqUbWgdvpyCsQWeYJJhWLCXrPsjGXkllyzrSsgGgaJXSCVVJjSGlmfoXtnKJVxTXAFmUQOMNwKENpwdieTrljvHtxpMJGNrhmXTwELzZlVPvwBYFPxwwZAbuhzSeEXDOkYgsBzGlSonWXtJH;n6fsf52adc'

from app import routes