import flask

flask_app = flask.Flask(__name__)
flask_app.config['SECRET_KEY'] = 'IPmwYmXQJirnGJIjitOIVViGuySNsNNfFluAWVDgOONPRkszzhSUCosxeRpEjLPFYCwGsAVSDnCMUYkMTKEBaCLOEBckrWCYALevkuLqaUXhEdWKcqUbWgdvpyCsQWeYJJhWLCXrPsjGXkllyzrSsgGgaJXSCVVJjSGlmfoXtnKJVxTXAFmUQOMNwKENpwdieTrljvHtxpMJGNrhmXTwELzZlVPvwBYFPxwwZAbuhzSeEXDOkYgsBzGlSonWXtJH;n6fsf52adc'

from app import routes